sudo: required

language: python

services:
      - docker

before_install:
      - curl -L https://github.com/docker/compose/releases/download/1.6.1/docker-compose-`uname -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin

script:
      - git clone https://github.com/chiminey/docker-chiminey.git
      - cd docker-chiminey
      - docker-compose up -d
      - docker-compose ps
