start_process_schedule:
	@sh ./start_process_schedule.sh

process_schedule_done:
	@sh ./process_schedule_done.sh

start_running_process:
	@echo running
	@sh ./start_running_process.sh

process_running_done:
	@echo checking for running
	@sh ./process_running_done.sh
