#!/bin/bash

# Version 2.0

top_directory=$1

echo ""
echo "iseed values from input/:"

grep iseed  $top_directory/input*/*/HRMC.inp_values

echo ""
echo "iseed values from output/:"
grep iseed  $top_directory/output*/*/HRMC.inp

echo ""
echo "tempK1 values from output/:"
grep 'Temperature (LINEAR QUENCH - Stage 2)'  $top_directory/output*/*/HRMC.inp


echo ""
echo "tempK2 values from output/:"
grep 'Temperature (LINEAR QUENCH - Stage 3)'  $top_directory/output*/*/HRMC.inp

echo ""
echo "istart values from output/:"
grep istart  $top_directory/output*/*/HRMC.inp_values

echo ""
echo "Sorted md5sum for xyz_final*. Only one duplicate expected"
find $top_directory  -name "xyz_final.xyz"  -exec md5sum {} \; | sort -k2

echo ""
echo "Sorted md5sum for xyz_final*. Only one duplicate expected"
find $top_directory  -name "xyz_final.xyz"  -exec md5sum {} \; | awk '{print $1}' | sort | uniq -c



echo ""
echo "Trace of run output selection"
find $top_directory/input* -maxdepth 1 -name "audit*"  -exec grep -v "spaw"  {} \;  | sort -k2 -n
