PROC_DESTINATION='chimineywd'

start_process_schedule:
	@sh ./start_process_schedule.sh $(PROC_DESTINATION)

process_schedule_done:
	@sh ./process_schedule_done.sh

start_running_process:
	@echo running
	@sh ./start_running_process.sh $(PROC_DESTINATION)

process_running_done:
	@echo checking for running
	@sh ./process_running_done.sh
